name: Build & Deploy
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Install deps
        run: npm ci
      - name: Build project
        run: npm run build
      - name: Upload Artifact # Дает доступ к статичным файлам
        uses: actions/upload-artifact@v4
        with:
          name: build-files # .*
          path: build
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Get build project
        uses: actions/download-artifact@v4 # для получения сбилдженого проекта(тех самых статичных файлов)
        with:
          name: build-files # тоже название которое мы дали при upload артифактов - .*